---
title: "stl_lead_inequity"
format: html
editor: visual
---

## 

Download the packages

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
```

Read the data

```{r}
stl_lead <- read_csv(here::here("Data","stl_blood_lead.csv")) %>% clean_names()

```

```{r}

stl_lead_prop <- stl_lead %>%
  dplyr::mutate(prop_white = (white / total_pop) * 100) 


```

Create a scatterplot

```{r}
stl_lead_plot = ggplot(data = stl_lead, aes(x=pct_elevated,
                             y=white)) +
  geom_point(size=2, alpha=0.5, color = "green") + labs(title = "My Graph")

stl_lead_plot
```

### Adding some text for description on the graph and color

Save the plot

```{r}
ggsave(plot = stl_lead_plot, here::here("Figs", "my_graph.jpeg"),
       width = 8,
       height = 8,
       dpi = 150)
```

Save the plot in specific dimention

```{r}
ggsave(plot = stl_lead_plot, here::here("Figs", "my_graph.png"),
       width = 6,
       height = 5,
       dpi = 150)
```

### 

###Creating a Histogram

```{r}
graph_hist <- ggplot(data=stl_lead, aes(x=pct_elevated)) + geom_histogram(color="blue", alpha = 0.8)

graph_hist
```

Export it to the Figs folder

```{r}
ggsave(plot = graph_hist, here::here("Figs", "my_hist_graph.jpg"))
```
